services:
  php:
    image: php:8.0-fpm
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8090:80"
    networks:
      - app-network

  web:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8081:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-container
    ports:
      - "8085:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: